---
- name: Ensure ~/.config/bash directory exists
  file:
    path: ~/.config/bash
    state: directory
    owner: usmon
    group: usmon
    mode: 0755

- name: Copy bash aliases and functions
  copy:
    src: "{{ item.src }}"
    dest: "~/.config/bash/{{ item.dest }}"
    owner: usmon
    group: usmon
    mode: 0744
  with_items:
    - { src: aliases, dest: aliases }
    - { src: functions, dest: functions }

- name: Copy bashrc and inputrc
  copy:
    src: "{{ item.src }}"
    dest: "~/{{ item.dest }}"
    owner: usmon
    group: usmon
    mode: 0744
  with_items:
    - { src: bashrc, dest: .bashrc }
    - { src: inputrc, dest: .inputrc }