---
- hosts: localhost
  connection: local

  pre_tasks:
    - name: Check for supported distributions
      vars:
        supported_distributions: [ "Archlinux" ]
      fail:
        msg: "Playbook currently supports {{ supported_distributions|join(', ') }} based distributions."
      when: ansible_os_family not in supported_distributions

    - name: Update package cache (Arch)
      become: true
      pacman: update_cache=yes
      changed_when: false
      when: ansible_os_family in [ "Archlinux" ]

  tasks:
    - name: Set roles
      set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles }}"

    - name: Display roles
      debug:
        var: run_roles

    - name: Run roles
      include_role:
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"