---
- name: Ensure git installed
  become: true
  package:
    name: git
    state: latest

- name: Setup git config
  copy:
    src: gitconfig
    dest: ~/.gitconfig
    owner: usmon
    group: usmon
    mode: 0700